
services:
  cypress:
    build: .
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
      - ./reports:/e2e/cypress/reports
    command:
      - "--reporter"
      - "cypress-mochawesome-reporter"
