version: '3.8'

services:
  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cypress_tests
    working_dir: /e2e
    volumes:
      - .:/e2e # Mount the current directory into /e2e in the container
    command: ["cypress", "run"] # Default command to run Cypress tests interactively
